development:
  bucket: com-pulse-places
  access_key_id: 0CVE2XVHB1F3BHJ0QEG2
  secret_access_key: fTJo0cjkPm5L2EO4vX3IyHo6w89m88f0u+gMoPjb
  
test:
  bucket_name: appname_test
  access_key_id: 
  secret_access_key: 

production:
  bucket_name: appname
  access_key_id: 
  secret_access_key: 
