insert activities (name,category) values('Art','Arts, Entertainment & Culture');
insert activities (name,category) values('Books','Arts, Entertainment & Culture');
insert activities (name,category) values('Comedy','Arts, Entertainment & Culture');
insert activities (name,category) values('Crafts','Arts, Entertainment & Culture');
insert activities (name,category) values('Dance','Arts, Entertainment & Culture');
insert activities (name,category) values('Galleries','Arts, Entertainment & Culture');
insert activities (name,category) values('Karaoke','Arts, Entertainment & Culture');
insert activities (name,category) values('Language','Arts, Entertainment & Culture');
insert activities (name,category) values('Mime','Arts, Entertainment & Culture');
insert activities (name,category) values('Movies','Arts, Entertainment & Culture');
insert activities (name,category) values('Museums','Arts, Entertainment & Culture');
insert activities (name,category) values('Music','Arts, Entertainment & Culture');
insert activities (name,category) values('Photography','Arts, Entertainment & Culture');
insert activities (name,category) values('Quiz','Arts, Entertainment & Culture');
insert activities (name,category) values('Theatre','Arts, Entertainment & Culture');
insert activities (name,category) values('Other','Arts, Entertainment & Culture');
insert activities (name,category) values('Entrepreneurs','Business & Career');
insert activities (name,category) values('Small Business','Business & Career');
insert activities (name,category) values('Training','Business & Career');
insert activities (name,category) values('Other','Business & Career');
insert activities (name,category) values('Charity','Communities & Lifestyles');
insert activities (name,category) values('Community ','Communities & Lifestyles');
insert activities (name,category) values('Sustainability','Communities & Lifestyles');
insert activities (name,category) values('Other','Communities & Lifestyles');
insert activities (name,category) values('Cooking','Eating & Drinking');
insert activities (name,category) values('Drinking','Eating & Drinking');
insert activities (name,category) values('Eating','Eating & Drinking');
insert activities (name,category) values('Markets','Eating & Drinking');
insert activities (name,category) values('Wine appreciation','Eating & Drinking');
insert activities (name,category) values('Other','Eating & Drinking');
insert activities (name,category) values('Alternative Health','Health and fitness');
insert activities (name,category) values('Massage','Health and fitness');
insert activities (name,category) values('Meditation','Health and fitness');
insert activities (name,category) values('Nutrition','Health and fitness');
insert activities (name,category) values('Other','Health and fitness');
insert activities (name,category) values('Cats','Pets and Animals');
insert activities (name,category) values('Dogs','Pets and Animals');
insert activities (name,category) values('Fish','Pets and Animals');
insert activities (name,category) values('Horses','Pets and Animals');
insert activities (name,category) values('Sheep','Pets and Animals');
insert activities (name,category) values('Other','Pets and Animals');
insert activities (name,category) values('Camping','Sports and Outdoorsy stuff');
insert activities (name,category) values('Cycling','Sports and Outdoorsy stuff');
insert activities (name,category) values('Fitness classes','Sports and Outdoorsy stuff');
insert activities (name,category) values('Football','Sports and Outdoorsy stuff');
insert activities (name,category) values('Golf','Sports and Outdoorsy stuff');
insert activities (name,category) values('Hiking','Sports and Outdoorsy stuff');
insert activities (name,category) values('Horse racing','Sports and Outdoorsy stuff');
insert activities (name,category) values('Motor racing','Sports and Outdoorsy stuff');
insert activities (name,category) values('Pilates','Sports and Outdoorsy stuff');
insert activities (name,category) values('Rollerblading','Sports and Outdoorsy stuff');
insert activities (name,category) values('Rugby','Sports and Outdoorsy stuff');
insert activities (name,category) values('Running','Sports and Outdoorsy stuff');
insert activities (name,category) values('Sailing','Sports and Outdoorsy stuff');
insert activities (name,category) values('Skiing','Sports and Outdoorsy stuff');
insert activities (name,category) values('Squash','Sports and Outdoorsy stuff');
insert activities (name,category) values('Tennis','Sports and Outdoorsy stuff');
insert activities (name,category) values('Walking','Sports and Outdoorsy stuff');
insert activities (name,category) values('Yoga','Sports and Outdoorsy stuff');
insert activities (name,category) values('Other','Sports and Outdoorsy stuff');
insert activities (name,category) values('Camping','Travel');
insert activities (name,category) values('Short-breaks','Travel');
insert activities (name,category) values('Skiing','Travel');
insert activities (name,category) values('Other','Travel');