class AddNewMatchingViews < ActiveRecord::Migration
   def self.up
     
     
     execute("create view vcommon as select vcommon_union.fb_user_id1 AS fb_user_id1,vcommon_union.fb_user_name1 AS fb_user_name1,vcommon_union.fb_user_source_id1 AS fb_user_source_id1,vcommon_union.fb_user_id2 AS fb_user_id2,vcommon_union.fb_user_name2 AS fb_user_name2,vcommon_union.fb_user_source_id2 AS fb_user_source_id2,sum(vcommon_union.weight) AS sum(weight),sum(vcommon_union.cnt) AS sum(cnt) from vcommon_union group by vcommon_union.fb_user_id1,vcommon_union.fb_user_name1,vcommon_union.fb_user_source_id1,vcommon_union.fb_user_id2,vcommon_union.fb_user_name2,vcommon_union.fb_user_source_id2 having (sum(vcommon_union.cnt) > 1) order by vcommon_union.weight desc")
     execute("create view vcommon_union as select vlikes.fb_user_id1 AS fb_user_id1,vlikes.fb_user_name1 AS fb_user_name1,vlikes.fb_user_source_id1 AS fb_user_source_id1,vlikes.fb_user_id2 AS fb_user_id2,vlikes.fb_user_name2 AS fb_user_name2,vlikes.fb_user_source_id2 AS fb_user_source_id2,vlikes.weight AS weight,vlikes.cnt AS cnt from vlikes union select vevents.fb_user_id1 AS fb_user_id1,vevents.fb_user_name1 AS fb_user_name1,vevents.fb_user_source_id1 AS fb_user_source_id1,vevents.fb_user_id2 AS fb_user_id2,vevents.fb_user_name2 AS fb_user_name2,vevents.fb_user_source_id2 AS fb_user_source_id2,vevents.weight AS weight,vevents.cnt AS cnt from vevents")
     execute("create view vlikes as select vcommon_likes.fb_user_id1 AS fb_user_id1,vcommon_likes.fb_user_name1 AS fb_user_name1,vcommon_likes.fb_user_source_id1 AS fb_user_source_id1,vcommon_likes.fb_user_id2 AS fb_user_id2,vcommon_likes.fb_user_name2 AS fb_user_name2,vcommon_likes.fb_user_source_id2 AS fb_user_source_id2,sum(vlike_points.weight) AS weight,count(0) AS cnt from (vcommon_likes join vlike_points on((vlike_points.like_id = vcommon_likes.like_id))) group by vcommon_likes.fb_user_id1,vcommon_likes.fb_user_name1,vcommon_likes.fb_user_id2,vcommon_likes.fb_user_name2 order by sum(vlike_points.weight) desc")
     execute("create view vevents as select vcommon_event.fb_user_id1 AS fb_user_id1,vcommon_event.fb_user_name1 AS fb_user_name1,vcommon_event.fb_user_source_id1 AS fb_user_source_id1,vcommon_event.fb_user_id2 AS fb_user_id2,vcommon_event.fb_user_name2 AS fb_user_name2,vcommon_event.fb_user_source_id2 AS fb_user_source_id2,sum(vcommon_event.weight) AS weight,count(0) AS cnt from vcommon_event group by vcommon_event.fb_user_id1,vcommon_event.fb_user_name1,vcommon_event.fb_user_source_id1,vcommon_event.fb_user_id2,vcommon_event.fb_user_name2,vcommon_event.fb_user_source_id2 order by sum(vcommon_event.weight) desc")

     execute("create view vcommon_likes as select distinct L1.fb_user_id AS fb_user_id1,U1.name AS fb_user_name1,U1.fb_user_source_id AS fb_user_source_id1,L2.fb_user_id AS fb_user_id2,U2.name AS fb_user_name2,U2.fb_user_source_id AS fb_user_source_id2,L1.like_name AS like_name,L1.category AS category,L1.like_id AS like_id from (((fb_user_likes L1 join fb_user_likes L2 on(((L1.like_id = L2.like_id) and (L1.fb_user_id <> L2.fb_user_id)))) join fb_users U1 on((U1.fb_user_id = L1.fb_user_id))) join fb_users U2 on((U2.fb_user_id = L2.fb_user_id))) where (((U1.gender is not null) or (U2.gender is not null) or (U1.gender <> U2.gender)) and ((U1.relationship = 'single') or isnull(U1.relationship)) and ((U2.relationship = 'single') or isnull(U2.relationship)) and (U1.fb_user_id > U2.fb_user_id)) order by U1.name,U2.name")

     execute("create view vcommon_event as select vcommon_events_loc.fb_user_id1 AS fb_user_id1,vcommon_events_loc.fb_user_source_id1 AS fb_user_source_id1,vcommon_events_loc.fb_user_name1 AS fb_user_name1,vcommon_events_loc.fb_user_id2 AS fb_user_id2,vcommon_events_loc.fb_user_source_id2 AS fb_user_source_id2,vcommon_events_loc.fb_user_name2 AS fb_user_name2,vcommon_events_loc.event_location1 AS event_location1,vcommon_events_loc.event_location2 AS event_location2,vcommon_events_loc.weight AS weight,vcommon_events_loc.cnt AS cnt from vcommon_events_loc union select vcommon_events_evt.fb_user_id1 AS fb_user_id1,vcommon_events_evt.fb_user_source_id1 AS fb_user_source_id1,vcommon_events_evt.fb_user_name1 AS fb_user_name1,vcommon_events_evt.fb_user_id2 AS fb_user_id2,vcommon_events_evt.fb_user_source_id2 AS fb_user_source_id2,vcommon_events_evt.fb_user_name2 AS fb_user_name2,vcommon_events_evt.event_location1 AS event_location1,vcommon_events_evt.event_location2 AS event_location2,vcommon_events_evt.weight AS weight,vcommon_events_evt.cnt AS cnt from vcommon_events_evt")
     
     execute("create view vcommon_event_loc as select distinct E1.fb_user_id AS fb_user_id1,U1.fb_user_source_id AS fb_user_source_id1,U1.name AS fb_user_name1,E2.fb_user_id AS fb_user_id2,U2.fb_user_source_id AS fb_user_source_id2,U2.name AS fb_user_name2,E1.event_location AS event_location1,E2.event_location AS event_location2,0.6 AS weight,1 AS cnt from (((fb_user_events E1 join fb_user_events E2 on(((E1.event_location = E2.event_location) and (E1.event_id <> E2.event_id) and (E1.fb_user_id <> E2.fb_user_id)))) join fb_users U1 on((U1.fb_user_id = E1.fb_user_id))) join fb_users U2 on((U2.fb_user_id = E2.fb_user_id))) where ((isnull(U1.gender) or isnull(U2.gender) or (U1.gender <> U2.gender)) and ((U1.relationship = 'single') or isnull(U1.relationship)) and ((U2.relationship = 'single') or isnull(U2.relationship)) and (E1.event_location not in ('Our House','Everywhere','My House','worldwide','global','london','international','tbc','','south africa')) and (E1.fb_user_id < E2.fb_user_id)) order by U1.name,U2.name")
     
    execute("create view  vcommon_event_evt as select distinct E1.fb_user_id AS fb_user_id1,U1.fb_user_source_id AS fb_user_source_id1,U1.name AS fb_user_name1,E2.fb_user_id AS fb_user_id2,U2.fb_user_source_id AS fb_user_source_id2,U2.name AS fb_user_name2,E1.event_location AS event_location1,E2.event_location AS event_location2,1 AS weight,1 AS cnt from (((fb_user_events E1 join fb_user_events E2 on(((E1.event_id = E2.event_id) and (E1.fb_user_id <> E2.fb_user_id)))) join fb_users U1 on((U1.fb_user_id = E1.fb_user_id))) join fb_users U2 on((U2.fb_user_id = E2.fb_user_id))) where ((isnull(U1.gender) or isnull(U2.gender) or (U1.gender <> U2.gender)) and ((U1.relationship = 'single') or isnull(U1.relationship)) and ((U2.relationship = 'single') or isnull(U2.relationship)) and (E1.fb_user_id < E2.fb_user_id))")
     
     execute("create  view vlike_points as select fb_user_likes.like_name AS like_name,w.category AS category,fb_user_likes.like_id AS like_id,count(0) AS count(*),(1 - (count(0) / 1500)) AS points,(((1 - (count(0) / 1500)) - 0.887) * 10) AS ((1 - (count(0) / 1500)) - 0.887)*10,(w.weighting / 10) AS weighting/10,(((1 - (count(0) / 1500)) - 0.887) * w.weighting) AS weight from (fb_user_likes join like_weighting w on((w.category = fb_user_likes.category))) where (w.weighting > 0) group by fb_user_likes.like_name,fb_user_likes.like_id order by count(0) desc")
       
       

  end

  def self.down

  end
end
